=== oskarklos2006/Projects_Oskar_Klos/HiH Projekt I/PROJEKTXSD.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="website">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="topic"/>
				<xs:element ref="content"/>
				<xs:element ref="gallery"/>
				<xs:element ref="links"/>
				<xs:element name="survey" type="surveyType"/>
				<xs:element name="menu" type="menuType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="topic">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="shorttext"/>
				<xs:element name="author" type="authortype"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="authortype">
		<xs:all>
			<xs:element name="name" type="shorttext"/>
			<xs:element name="surname" type="shorttext"/>
			<xs:element name="studentid" type="shortint"/>
		</xs:all>
	</xs:complexType>

	<xs:element name="content">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="introduction" type="introductionType"/>
				<xs:element name="favouritebands" type="bandsType"/>
				<xs:element name="favouritesongs" type="songsType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="introductionType">
		<xs:sequence>
			<xs:element name="headline" type="shorttext"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="aboutlist">
				<xs:simpleType>
					<xs:list itemType="shorttext"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="bandsType">
		<xs:sequence>
			<xs:element name="band" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="rank" type="xs:integer" use="required"/>
					<xs:attribute name="name" type="shorttext" use="required"/>
					<xs:attribute name="performer" type="performerType"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="performerType">
		<xs:restriction base="xs:string">
			<xs:pattern value="band|solo"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="songsType">
		<xs:sequence>
			<xs:element name="topsongs">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="song" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="rank" type="xs:integer" use="required"/>
								<xs:attribute name="title" type="xs:string" use="required"/>
								<xs:attribute name="artist" type="shorttext" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="gallery">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="photos">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="photo" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attributeGroup ref="sources"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:attributeGroup name="sources">
		<xs:attribute name="source" type="xs:anyURI" use="required"/>
		<xs:attribute name="label" type="longtext" use="required"/>
	</xs:attributeGroup>

	<xs:element name="links">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="link" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attributeGroup ref="sources"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="surveyType">
		<xs:sequence>
			<xs:element name="question" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="text" type="unionType"/>
						<xs:element name="response">
							<xs:complexType>
								<xs:attribute name="type" type="responseType" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>				
	</xs:complexType>
	
	<xs:simpleType name="unionType">
		<xs:union memberTypes="shorttext longtext"/>
	</xs:simpleType>
	
	<xs:simpleType name="responseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="numeric"/>
			<xs:enumeration value="selection"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="menuType">	
		<xs:sequence>
			<xs:element name="option" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="id" type="xs:string" use="required"/>
							<xs:attribute name="reference" type="shorttext" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="shorttext">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="longtext">
		<xs:restriction base="xs:string">
			<xs:minLength value="10"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="shortint">
		<xs:restriction base="xs:integer">
			<xs:totalDigits value="6"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== oskarklos2006/Projects_Oskar_Klos/HiH Projekt I/PROJEKTXML_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="PROJEKTXSD.xsd">
	<topic>
		<title>My Hobby</title>
		<author>
			<name>Oskar</name>
			<surname>Kłos</surname>
			<studentid>203708</studentid>
		</author>
	</topic>
	<content>
		<introduction>
			<headline>Introduction</headline>
			<description> Welcome to my website! Here, I share my passion for timeless music from the '70s, '80s, and '90s. </description>
			<aboutlist> Bands Artists Songs Biographies </aboutlist>
		</introduction>
		<favouritebands>
			<band rank="1" name="Michael Jackson" performer="solo">
				<description>Michael Jackson (1958–2009), often referred to as the "King of Pop," was an American singer, songwriter, and dancer.</description>
			</band>
			<band rank="2" name="The Beatles" performer="band">
				<description>The Beatles were an iconic British rock band formed in Liverpool in 1960, consisting of John Lennon, Paul McCartney, George Harrison, and Ringo Starr.</description>
			</band>
			<band rank="3" name="Queen" performer="band">
				<description>Queen, formed in London in 1970, is a legendary British rock band known for their theatrical performances and genre-blending music.</description>
			</band>
			<band rank="4" name="Madonna" performer="solo">
				<description>Madonna, often called the "Queen of Pop," is a globally recognized artist known for her groundbreaking influence on music, fashion, and pop culture.</description>
			</band>
			<band rank="5" name="Nirvana" performer="band">
				<description>Nirvana was an American rock band formed in 1987 in Aberdeen, Washington, by Kurt Cobain and Krist Novoselic.</description>
			</band>
		</favouritebands>
		<favouritesongs>
			<topsongs>
				<song rank="1" title="Earth Song" artist="Michael Jackson"/>
				<song rank="2" title="Forever Young" artist="Alphaville"/>
				<song rank="3" title="Killing Me Softly with His Song" artist="Fugees, Ms. Lauryn Hill"/>
				<song rank="4" title="Wonderwall" artist="Oasis"/>
				<song rank="5" title="All I Want for Christmas Is You" artist="Mariah Carey"/>
			</topsongs>
		</favouritesongs>
	</content>
	<gallery>
		<photos>
			<photo source="./widownia.jpg" label="Concert Audience"/>
			<photo source="./artist.jpg" label="The top 5 artist"/>
			<photo source="./band.jpg" label="The top 5 band"/>
		</photos>
	</gallery>
	<links>
		<link source="https://www.w3schools.com/html/" label="HTML w3schools"/>
		<link source="https://www.w3schools.com/xml/default.asp" label="XML w3schools"/>
		<link source="https://enauczanie.pg.edu.pl/moodle/" label="Moodle website"/>
	</links>
	<survey>
		<question id="q1">
			<text>Who is you favourite artist?</text>
			<response type="text"/>
		</question>
		<question id="q2">
			<text>What is your favourite band?</text>
			<response type="text"/>
		</question>
		<question id="q3">
			<text>How old are you?</text>
			<response type="numeric"/>
		</question>
		<question id="q4">
			<text>Do you like my website?</text>
			<response type="selection"/>
		</question>
	</survey>
	<menu>
		<option id="o1" reference="top">Go back to top</option>
		<option id="o2" reference="favouritebands">Top 5 Bands and Artists</option>
		<option id="o3" reference="favouritesongs">Top 5 Songs</option>
		<option id="o4" reference="survey">Survey</option>
	</menu>
</website>
